FROM golang:1.16

WORKDIR /pb

RUN apt-get update
RUN apt install -y protobuf-compiler

RUN go get google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1 \ 
    google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0 \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway

RUN curl -o /usr/local/include/google/api/annotations.proto --create-dirs https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/annotations.proto && \
    curl -o /usr/local/include/google/api/http.proto --create-dirs https://raw.githubusercontent.com/googleapis/googleapis/master/google/api/http.proto