// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetPriceParams creates a new GetPriceParams object
//
// There are no default values defined in the spec.
func NewGetPriceParams() GetPriceParams {

	return GetPriceParams{}
}

// GetPriceParams contains all the bound params for the get price operation
// typically these are obtained from a http.Request
//
// swagger:parameters getPrice
type GetPriceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Date in format YYYY-MM-DD
	  Required: true
	  In: path
	*/
	Date strfmt.Date
	/*Stock's code
	  Required: true
	  In: path
	*/
	Ticker string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPriceParams() beforehand.
func (o *GetPriceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rDate, rhkDate, _ := route.Params.GetOK("date")
	if err := o.bindDate(rDate, rhkDate, route.Formats); err != nil {
		res = append(res, err)
	}

	rTicker, rhkTicker, _ := route.Params.GetOK("ticker")
	if err := o.bindTicker(rTicker, rhkTicker, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDate binds and validates parameter Date from path.
func (o *GetPriceParams) bindDate(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	// Format: date
	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("date", "path", "strfmt.Date", raw)
	}
	o.Date = *(value.(*strfmt.Date))

	if err := o.validateDate(formats); err != nil {
		return err
	}

	return nil
}

// validateDate carries on validations for parameter Date
func (o *GetPriceParams) validateDate(formats strfmt.Registry) error {

	if err := validate.FormatOf("date", "path", "date", o.Date.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindTicker binds and validates parameter Ticker from path.
func (o *GetPriceParams) bindTicker(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Ticker = raw

	return nil
}
