// Code generated by go-swagger; DO NOT EDIT.

package stock

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPriceHandlerFunc turns a function with the right signature into a get price handler
type GetPriceHandlerFunc func(GetPriceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPriceHandlerFunc) Handle(params GetPriceParams) middleware.Responder {
	return fn(params)
}

// GetPriceHandler interface for that can handle valid get price params
type GetPriceHandler interface {
	Handle(GetPriceParams) middleware.Responder
}

// NewGetPrice creates a new http.Handler for the get price operation
func NewGetPrice(ctx *middleware.Context, handler GetPriceHandler) *GetPrice {
	return &GetPrice{Context: ctx, Handler: handler}
}

/* GetPrice swagger:route GET /price/{ticker}/{date} stock getPrice

getPrice

Get stock price

*/
type GetPrice struct {
	Context *middleware.Context
	Handler GetPriceHandler
}

func (o *GetPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPriceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
