// Code generated by mockery (devel). DO NOT EDIT.

package mock

import (
	model "github.com/andreipimenov/golang-training-2021/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *Repository) Load(_a0 string) (model.Price, bool) {
	ret := _m.Called(_a0)

	var r0 model.Price
	if rf, ok := ret.Get(0).(func(string) model.Price); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(model.Price)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *Repository) Store(_a0 string, _a1 model.Price) {
	_m.Called(_a0, _a1)
}
