// Code generated by mockery (devel). DO NOT EDIT.

package mock

import (
	time "time"

	model "github.com/andreipimenov/golang-training-2021/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetPrice provides a mock function with given fields: _a0, _a1
func (_m *Service) GetPrice(_a0 string, _a1 time.Time) (*model.Price, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.Price
	if rf, ok := ret.Get(0).(func(string, time.Time) *model.Price); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Price)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
